import assert from 'node:assert/strict';
import test from 'node:test';
import { verifyOnchain, BASE_USDC, TRANSFER_TOPIC } from '../lib/onchain-verifier.mjs';

const receiver='0x6D1CCe697B145E6D8DB31B038F5D7fbc4Fe27B28';
const payer='0x1111111111111111111111111111111111111111';
const tx='0x'+'a'.repeat(64);
const topic=a=>'0x'+'0'.repeat(24)+a.slice(2);
const rpc=({chain='0x2105',status='0x1',token=BASE_USDC,to=receiver,value='0x'+'0'.repeat(59)+'186a0',block='0x64'}={})=>async(_url,{body})=>{const q=JSON.parse(body); let result; if(q.method==='eth_chainId')result=chain; else if(q.method==='eth_blockNumber')result='0x65'; else result={status,blockNumber:block,logs:[{address:token,topics:[TRANSFER_TOPIC,topic(payer),topic(to)],data:value,logIndex:'0x0'}]}; return {ok:true,json:async()=>({jsonrpc:'2.0',id:1,result})};};
const base={txHash:tx,receiver,rpcUrl:'https://rpc.test',minConfirmations:'2',timeoutMs:1000};

test('valid canonical Base USDC transfer verifies',async()=>{const x=await verifyOnchain({...base,fetchImpl:rpc()}); assert.equal(x.verified,true);});
test('wrong chain is rejected',async()=>{const x=await verifyOnchain({...base,fetchImpl:rpc({chain:'0x14a34'})}); assert.equal(x.errorCode,'WRONG_CHAIN');});
test('wrong token and receiver are rejected',async()=>{assert.equal((await verifyOnchain({...base,fetchImpl:rpc({token:'0x'+'2'.repeat(40)})})).errorCode,'NO_USDC_TRANSFER'); assert.equal((await verifyOnchain({...base,fetchImpl:rpc({to:'0x2222222222222222222222222222222222222222'})})).errorCode,'NO_USDC_TRANSFER');});
test('wrong expected amount and insufficient confirmations are explicit',async()=>{assert.equal((await verifyOnchain({...base,expected:{amountAtomic:'999'},fetchImpl:rpc()})).errorCode,'WRONG_AMOUNT'); const x=await verifyOnchain({...base,minConfirmations:'3',fetchImpl:rpc()}); assert.equal(x.errorCode,'INSUFFICIENT_CONFIRMATIONS');});
test('malformed tx and missing receipt are safe',async()=>{assert.equal((await verifyOnchain({txHash:'0x12',receiver,rpcUrl:'https://rpc.test',fetchImpl:rpc()})).errorCode,'MALFORMED_TX_HASH'); assert.equal((await verifyOnchain({receiptId:'ck_receipt_12345678',receiver,rpcUrl:'https://rpc.test',getReceipt:()=>null,fetchImpl:rpc()})).errorCode,'RECEIPT_NOT_FOUND');});
test('reverted and missing transaction are explicit',async()=>{assert.equal((await verifyOnchain({...base,fetchImpl:rpc({status:'0x0'})})).errorCode,'TX_REVERTED'); const f=async(_u,{body})=>{const q=JSON.parse(body); return {ok:true,json:async()=>({jsonrpc:'2.0',id:1,result:q.method==='eth_chainId'?'0x2105':null})};}; assert.equal((await verifyOnchain({...base,fetchImpl:f})).errorCode,'TX_NOT_FOUND');});
test('fallback agreement and conflict are handled',async()=>{const x=await verifyOnchain({...base,rpcUrl:'https://a',fallbackRpcUrl:'https://b',fetchImpl:rpc()}); assert.equal(x.verified,true); const conflict=async(_u,{body})=>{const q=JSON.parse(body); if(q.method==='eth_chainId')return {ok:true,json:async()=>({jsonrpc:'2.0',id:1,result:'0x2105'})}; return rpc({value:'0x'+'0'.repeat(63)+'2'})(_u,{body});}; const y=await verifyOnchain({...base,rpcUrl:'https://a',fallbackRpcUrl:'https://b',fetchImpl:async(_u,o)=>_u.includes('a')?rpc()(_u,o):conflict(_u,o)}); assert.equal(y.errorCode,'RPC_INCONSISTENT');});
test('missing target and invalid confirmation configuration are distinct',async()=>{assert.equal((await verifyOnchain({receiver,rpcUrl:'x',fetchImpl:rpc()})).errorCode,'MISSING_VERIFICATION_TARGET'); assert.equal((await verifyOnchain({...base,minConfirmations:'nope',fetchImpl:rpc()})).errorCode,'INVALID_CONFIGURATION');});
test('RPC timeout, JSON-RPC error, malformed response, and HTTP failure are uncertain',async()=>{const timeout=async()=>{throw Object.assign(new Error('timeout'),{name:'AbortError'})}; assert.equal((await verifyOnchain({...base,fetchImpl:timeout})).errorCode,'RPC_UNAVAILABLE'); const error=async()=>({ok:true,json:async()=>({jsonrpc:'2.0',id:1,error:{message:'denied'}})}); assert.equal((await verifyOnchain({...base,fetchImpl:error})).errorCode,'RPC_UNAVAILABLE'); const malformed=async()=>({ok:true,json:async()=>({hello:'world'})}); assert.equal((await verifyOnchain({...base,fetchImpl:malformed})).errorCode,'RPC_UNAVAILABLE'); const http=async()=>({ok:false,status:503}); assert.equal((await verifyOnchain({...base,fetchImpl:http})).errorCode,'RPC_UNAVAILABLE');});
test('malformed transfer and multiple transfers are deterministic',async()=>{const malformed=async(_u,{body})=>{const q=JSON.parse(body); return {ok:true,json:async()=>({jsonrpc:'2.0',id:1,result:q.method==='eth_chainId'?'0x2105':q.method==='eth_blockNumber'?'0x65':{status:'0x1',blockNumber:'0x64',logs:[{address:BASE_USDC,topics:[TRANSFER_TOPIC],data:'0x'}]}})};}; assert.equal((await verifyOnchain({...base,fetchImpl:malformed})).errorCode,'VERIFICATION_UNKNOWN'); const many=rpc(); const txResponse=async(_u,o)=>{const q=JSON.parse(o.body); if(q.method==='eth_chainId')return {ok:true,json:async()=>({jsonrpc:'2.0',id:1,result:'0x2105'})}; if(q.method==='eth_blockNumber')return {ok:true,json:async()=>({jsonrpc:'2.0',id:1,result:'0x65'})}; const r=await many(_u,o); const b=await r.json(); b.result.logs.push(b.result.logs[0]); return {ok:true,json:async()=>b};}; assert.equal((await verifyOnchain({...base,fetchImpl:txResponse})).errorCode,'VERIFICATION_UNKNOWN');});
test('receipt-backed expectations, association, legacy compatibility and integrity',async()=>{const receipt={id:'ck_receipt_12345678',purchaseId:'p1',entitlementId:'e1',capability:'artifact.integrity_manifest',holder:payer,payment:{transaction:tx,network:'eip155:8453',asset:BASE_USDC,payTo:receiver,amount:'100000'}}; let bound; const getReceipt=id=>id===receipt.id?receipt:null; const proof=await verifyOnchain({receiptId:receipt.id,receiver,rpcUrl:'x',getReceipt,bindProof:(_id,p)=>{bound=p},fetchImpl:rpc()}); assert.equal(proof.verified,true); assert.equal(bound.receiptId,receipt.id); assert.equal(proof.purchaseId,'p1'); assert.equal((await verifyOnchain({receiptId:receipt.id,txHash:'0x'+'b'.repeat(64),receiver,rpcUrl:'x',getReceipt,fetchImpl:rpc()})).errorCode,'RECEIPT_MISMATCH'); assert.equal(receipt.payment.amount,'100000');});
test('direct hash mode reports unavailable CrossingKey linkage',async()=>{const x=await verifyOnchain({...base,fetchImpl:rpc()}); assert.equal(x.purchaseMatch,null); assert.equal(x.entitlementMatch,null); assert.equal(x.receiptMatch,null); assert.equal(x.payment.payer,payer);});
test('stored receiver, token, network and payer mismatches are rejected',async()=>{const stored={id:'ck_receipt_12345678',payment:{transaction:tx,amount:'100000',payTo:'0x2222222222222222222222222222222222222222',asset:BASE_USDC,network:'eip155:8453'},holder:payer}; const getReceipt=()=>stored; assert.equal((await verifyOnchain({receiptId:stored.id,receiver,rpcUrl:'x',getReceipt,fetchImpl:rpc()})).errorCode,'RECEIPT_MISMATCH'); assert.equal((await verifyOnchain({receiptId:stored.id,receiver,rpcUrl:'x',expected:{token:'0x'+'2'.repeat(40)},getReceipt,fetchImpl:rpc()})).errorCode,'RECEIPT_MISMATCH'); assert.equal((await verifyOnchain({receiptId:stored.id,receiver,rpcUrl:'x',expected:{network:'eip155:84532'},getReceipt,fetchImpl:rpc()})).errorCode,'RECEIPT_MISMATCH');});
